# This file contains values from Cookiecutter

default_context:
  project_name: "aiothinkingcleaner"
  project_description: "Library to communicate with a Thinking Cleaner module asynchronously"
  organization: "matthijs2704"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "matthijs2704"
  email: "matthijs@logemann.dev"
  version: "0.1.0"
  line_length: "80"
  create_example_template: "none"
